'use client';
import { useState } from 'react';

export default function LandingScreen({ onStart }) {
    const [showTerms, setShowTerms] = useState(false);

    return (
        <section className="screen active" id="landing">
            <div className="graveyard-bg">
                <div className="moon"><div className="moon-crater moon-crater-1" /><div className="moon-crater moon-crater-2" /><div className="moon-crater moon-crater-3" /></div>
                <div className="dead-tree tree-left"><div className="trunk" /><div className="branch branch-1" /><div className="branch branch-2" /><div className="branch branch-3" /></div>
                <div className="dead-tree tree-right"><div className="trunk" /><div className="branch branch-1" /><div className="branch branch-2" /></div>
                <div className="tombstone tombstone-1"><div className="tombstone-stone"><span className="tombstone-text">R.I.P<br /><small>Data Entry<br />2020-2024</small></span></div></div>
                <div className="tombstone tombstone-2"><div className="tombstone-stone"><span className="tombstone-text">HERE LIES<br /><small>Your 9-to-5<br />Comfort Zone</small></span></div></div>
                <div className="tombstone tombstone-3"><div className="tombstone-stone"><span className="tombstone-text">R.I.P<br /><small>Copy-Paste<br />Warriors</small></span></div></div>
                <div className="tombstone tombstone-4"><div className="tombstone-stone"><span className="tombstone-text">GONE<br /><small>Forgotten<br />(JK)</small></span></div></div>
                <div className="ground" />
                <div className="ground-grass" />
            </div>
            <div className="landing-content">
                <div className="skull-icon">💀</div>
                <h1 className="glitch-text" data-text="REPLACED">REPLACED</h1>
                <p className="landing-subtitle">Find Your Career&apos;s <span className="highlight-red">Expiry Date</span></p>
                <p className="landing-desc">AI is coming for your job. The only question is — <em>when?</em><br />Enter your details. Face the truth. Share the doom.</p>
                <button className="cta-btn" onClick={onStart}><span className="btn-text">Find My Termination Date</span><span className="btn-icon">⚰️</span><div className="btn-glow" /></button>
                <p className="landing-footer-text">Over <span className="counter-animate">13,847</span> careers already buried</p>
            </div>

            {/* T&C Link */}
            <button className="tc-link" onClick={() => setShowTerms(true)}>Terms & Conditions</button>

            {/* T&C Modal */}
            {showTerms && (
                <div className="tc-overlay" onClick={() => setShowTerms(false)}>
                    <div className="tc-modal" onClick={(e) => e.stopPropagation()}>
                        <button className="tc-close" onClick={() => setShowTerms(false)}>✕</button>
                        <h3 className="tc-title">⚠️ Disclaimer & Terms</h3>
                        <div className="tc-body">
                            <p><strong>Relax. None of this is real.</strong></p>
                            <p>All scores, predictions, roasts, and "career expiry dates" generated by <strong>isaireplacing.me</strong> are entirely fictional, imaginary, and meant purely for <strong>entertainment purposes</strong>.</p>
                            <p>We do not actually know when (or if) AI will replace your job. We're not career advisors, fortune tellers, or your HR department. The AI-generated "organisation insights" are speculative and should not be taken as factual statements about any company.</p>
                            <p>By using this tool, you acknowledge that:</p>
                            <ul>
                                <li>All results are <strong>assumed, satirical, and not based on real data</strong></li>
                                <li>This is a fun, viral experiment — <strong>nothing serious</strong></li>
                                <li>You won't sue us when AI actually does take your job 💀</li>
                                <li>Shared cards are generated for entertainment and social sharing only</li>
                            </ul>
                            <p className="tc-footer-note">By continuing to use isaireplacing.me, you agree to these terms. Now go find your career's expiry date. 🪦</p>
                        </div>
                    </div>
                </div>
            )}
        </section>
    );
}
