/* ==========================================
   REPLACED 💀 — Data: Scoring, Org Intel & Roasts
   ========================================== */

// ---- Role base risk scores (0-100) ----
export const ROLE_RISK = {
    "data entry": 96, "data entry operator": 96, "typist": 95,
    "administrative assistant": 88, "secretary": 90, "receptionist": 91,
    "office assistant": 87, "clerk": 89, "filing clerk": 93, "virtual assistant": 85,
    "customer support": 85, "customer service": 85, "customer care": 84,
    "call center": 90, "call center agent": 90, "bpo": 88,
    "cashier": 92, "bank teller": 90, "front desk": 88,
    "content writer": 82, "copywriter": 80, "blogger": 83,
    "technical writer": 72, "journalist": 75, "editor": 72,
    "social media manager": 76, "content creator": 72,
    "translator": 88, "transcriptionist": 95, "proofreader": 85,
    "graphic designer": 74, "ui designer": 72, "ux designer": 58,
    "ui/ux designer": 68, "ui ux designer": 68,
    "product designer": 55, "web designer": 72, "visual designer": 70,
    "motion designer": 58, "interior designer": 55,
    "fashion designer": 50, "animator": 62, "illustrator": 64,
    "software developer": 55, "software engineer": 55,
    "frontend developer": 62, "front end developer": 62,
    "backend developer": 56, "back end developer": 56,
    "full stack developer": 58, "fullstack developer": 58,
    "web developer": 64, "mobile developer": 58,
    "android developer": 58, "ios developer": 58,
    "devops engineer": 48, "cloud engineer": 45,
    "system administrator": 65, "sysadmin": 65,
    "network engineer": 55, "database administrator": 68,
    "embedded engineer": 40, "hardware engineer": 35, "game developer": 45,
    "data scientist": 42, "data analyst": 72, "data engineer": 48,
    "machine learning engineer": 32, "ml engineer": 32,
    "ai engineer": 28, "ai researcher": 25,
    "business intelligence": 65, "bi analyst": 65, "statistician": 55,
    "qa tester": 80, "qa engineer": 72, "manual tester": 92,
    "test engineer": 72, "automation tester": 52, "sdet": 50,
    "product manager": 42, "project manager": 52,
    "program manager": 48, "engineering manager": 38,
    "team lead": 40, "tech lead": 38,
    "scrum master": 62, "agile coach": 55,
    "manager": 45, "director": 35, "vp": 28,
    "ceo": 15, "cto": 18, "cfo": 20, "coo": 22, "cmo": 25,
    "founder": 12, "co-founder": 12,
    "business analyst": 65, "business consultant": 50,
    "management consultant": 48, "consultant": 48,
    "strategy consultant": 40, "operations manager": 50,
    "marketing": 68, "digital marketing": 74, "digital marketer": 74,
    "seo specialist": 76, "seo": 76, "sem": 74,
    "performance marketer": 72, "growth hacker": 60,
    "brand manager": 50, "marketing manager": 56,
    "sales": 50, "sales executive": 52, "sales manager": 45,
    "business development": 48, "bdm": 48, "bde": 52,
    "account manager": 50, "key account manager": 45,
    "relationship manager": 48, "insurance agent": 72,
    "real estate agent": 55,
    "accountant": 76, "chartered accountant": 66, "ca": 66,
    "auditor": 72, "bookkeeper": 90, "tax consultant": 62,
    "financial analyst": 64, "financial advisor": 50,
    "investment banker": 45, "trader": 56, "actuary": 52, "underwriter": 74,
    "hr": 62, "hr manager": 56, "human resources": 62,
    "recruiter": 74, "talent acquisition": 72,
    "hr executive": 66, "payroll": 84,
    "lawyer": 45, "advocate": 45, "attorney": 45,
    "legal counsel": 42, "paralegal": 74, "legal assistant": 78,
    "compliance officer": 56,
    "doctor": 28, "physician": 28, "surgeon": 20,
    "nurse": 25, "pharmacist": 56, "dentist": 35,
    "psychologist": 30, "therapist": 30,
    "radiologist": 62, "pathologist": 56,
    "lab technician": 66, "medical transcriptionist": 93,
    "teacher": 35, "professor": 30, "lecturer": 35,
    "trainer": 45, "tutor": 56, "teaching assistant": 66,
    "instructional designer": 62, "academic counselor": 50,
    "photographer": 68, "videographer": 56, "video editor": 64,
    "film director": 30, "musician": 40, "sound engineer": 50,
    "voice artist": 78, "actor": 35,
    "researcher": 38, "scientist": 32, "architect": 42,
    "civil engineer": 38, "mechanical engineer": 35,
    "electrical engineer": 38, "chemical engineer": 35,
    "chef": 22, "cook": 35, "driver": 80, "pilot": 42,
    "delivery": 82, "warehouse": 76, "logistics": 62,
    "supply chain": 58, "procurement": 64,
    "quality analyst": 70, "operations": 56,
    "security": 56, "cybersecurity": 35,
    "ethical hacker": 32, "penetration tester": 35,
    "ux researcher": 48, "user researcher": 48,
    "intern": 82, "fresher": 80, "trainee": 78,
};

// ---- Industry risk modifiers ----
export const INDUSTRY_RISK = {
    technology: 1.14, finance: 1.10, healthcare: 0.84,
    education: 0.86, ecommerce: 1.12, media: 1.08,
    manufacturing: 1.0, legal: 0.90, real_estate: 0.94,
    consulting: 1.04, government: 0.76, automotive: 1.06,
    telecom: 1.08, pharma: 0.88, hospitality: 0.90,
    logistics: 1.06, construction: 0.80, agriculture: 0.80,
    marketing_agency: 1.10, other: 1.0,
};

// ---- Org Database ----
export const ORG_DATABASE = {
    "google": { mod: 1.25, tier: "extreme", note: "Google literally builds the AI that replaces jobs. They've already cut teams using their own AI tools." },
    "openai": { mod: 1.30, tier: "extreme", note: "OpenAI is the company replacing your job. Working here means you're building your own replacement." },
    "anthropic": { mod: 1.28, tier: "extreme", note: "Anthropic is pushing AI boundaries daily. Every team here accelerates job automation." },
    "deepmind": { mod: 1.28, tier: "extreme", note: "DeepMind's mission is superhuman AI. Your job is a stepping stone in their roadmap." },
    "microsoft": { mod: 1.22, tier: "extreme", note: "Microsoft has embedded Copilot AI into EVERYTHING. They've publicly said AI will reshape every role." },
    "meta": { mod: 1.20, tier: "extreme", note: "Meta is going all-in on AI and has already restructured multiple teams around AI automation." },
    "amazon": { mod: 1.20, tier: "extreme", note: "Amazon uses AI for everything from warehouse robots to code reviews. They automate relentlessly." },
    "nvidia": { mod: 1.22, tier: "extreme", note: "NVIDIA literally builds the hardware powering AI. They ARE the engine of job automation." },
    "infosys": { mod: 1.20, tier: "very_high", note: "Infosys CEO publicly stated AI will transform 50% of jobs. They've already deployed AI across delivery." },
    "tcs": { mod: 1.18, tier: "very_high", note: "TCS has heavily invested in AI platforms and has been automating traditional IT roles aggressively." },
    "wipro": { mod: 1.18, tier: "very_high", note: "Wipro has committed billions to AI transformation. Their 'ai360' initiative touches every business unit." },
    "hcl": { mod: 1.16, tier: "very_high", note: "HCL Technologies has been rapidly deploying AI solutions across client projects and internal ops." },
    "hcl technologies": { mod: 1.16, tier: "very_high", note: "HCL Technologies has been rapidly deploying AI solutions across client projects and internal ops." },
    "tech mahindra": { mod: 1.15, tier: "very_high", note: "Tech Mahindra has launched multiple AI-first initiatives replacing traditional roles with automation." },
    "cognizant": { mod: 1.16, tier: "very_high", note: "Cognizant has been restructuring teams around AI capabilities, reducing headcount in automated areas." },
    "accenture": { mod: 1.18, tier: "very_high", note: "Accenture invested $3B in AI and has been the loudest voice about AI replacing traditional consulting work." },
    "ibm": { mod: 1.17, tier: "very_high", note: "IBM CEO said AI will replace 30% of back-office roles. They paused hiring for positions AI can handle." },
    "gyanmatrix": { mod: 1.24, tier: "extreme", note: "Gyanmatrix Technologies runs on AI-first principles. Design, development, and operations are all being automated." },
    "gyanmatrix technologies": { mod: 1.24, tier: "extreme", note: "Gyanmatrix Technologies runs on AI-first principles. Design, development, and operations are all being automated. Manual design work has essentially been eliminated." },
    "apple": { mod: 1.14, tier: "high", note: "Apple has been quietly building AI into every product. Their design tools are increasingly AI-powered." },
    "netflix": { mod: 1.15, tier: "high", note: "Netflix uses AI for everything — recommendations, content decisions, even thumbnail design." },
    "uber": { mod: 1.14, tier: "high", note: "Uber is automating heavily — from AI pricing to autonomous vehicles. Support and ops roles at high risk." },
    "tesla": { mod: 1.18, tier: "very_high", note: "Tesla is betting the company on AI and robotics. Elon has publicly said robots will do most work." },
    "salesforce": { mod: 1.16, tier: "high", note: "Salesforce has released Einstein AI across all products, directly replacing traditional CRM management roles." },
    "adobe": { mod: 1.20, tier: "very_high", note: "Adobe Firefly and Sensei AI are literally replacing designers, illustrators, and content creators in real-time." },
    "canva": { mod: 1.22, tier: "extreme", note: "Canva's AI can now do what graphic designers took days to do. They're democratizing design to the point of eliminating designers." },
    "deloitte": { mod: 1.12, tier: "high", note: "Deloitte has deployed AI across audit, consulting, and operations. Traditional analyst roles are being phased out." },
    "mckinsey": { mod: 1.14, tier: "high", note: "McKinsey literally published reports on how AI will replace millions of jobs. They practice what they preach." },
    "flipkart": { mod: 1.14, tier: "high", note: "Flipkart uses AI for supply chain, recommendations, and customer service. Automation is a core strategy." },
    "swiggy": { mod: 1.12, tier: "high", note: "Swiggy heavily uses AI for routing, customer support, and operations optimization." },
    "zomato": { mod: 1.12, tier: "high", note: "Zomato uses AI across delivery optimization, support automation, and content generation." },
    "razorpay": { mod: 1.14, tier: "high", note: "Razorpay is deeply tech-driven with AI powering fraud detection, risk, and customer operations." },
    "zoho": { mod: 1.12, tier: "high", note: "Zoho has integrated AI (Zia) across their entire product suite, automating sales, support, and analytics." },
    "freshworks": { mod: 1.14, tier: "high", note: "Freshworks has launched Freddy AI across all products, directly replacing human support and sales tasks." },
    "hdfc": { mod: 1.10, tier: "high", note: "HDFC Bank has been a pioneer in banking automation, using AI for loan processing, fraud, and customer service." },
    "icici": { mod: 1.08, tier: "high", note: "ICICI Bank uses AI extensively in retail banking, risk assessment, and back-office operations." },
    "sbi": { mod: 1.04, tier: "moderate", note: "SBI is modernizing with AI but as a government bank, the pace is slower than private counterparts." },
    "jpmorgan": { mod: 1.14, tier: "high", note: "JPMorgan uses AI for trading, risk, legal document review, and customer service at massive scale." },
    "goldman sachs": { mod: 1.14, tier: "high", note: "Goldman Sachs has replaced entire trading floors with AI algorithms." },
    "reliance": { mod: 1.06, tier: "moderate", note: "Reliance is investing in AI through Jio platforms, but traditional business units are slower to adopt." },
    "tata": { mod: 1.04, tier: "moderate", note: "Tata Group is exploring AI across conglomerate companies, but adoption varies widely by subsidiary." },
    "government": { mod: 0.78, tier: "low", note: "Government organisations are the slowest AI adopters due to red tape, unions, and bureaucracy." },
    "govt": { mod: 0.78, tier: "low", note: "Government jobs are the last frontier for AI. The paperwork alone would confuse any AI system." },
    "army": { mod: 0.75, tier: "low", note: "Military roles require physical presence and split-second human judgment. AI can't do push-ups. Yet." },
};

export const ORG_KEYWORDS = [
    { keywords: ["ai", "artificial intelligence", "machine learning", "ml ", "deep learning"], mod: 1.22, note: "This company's name screams AI. They're clearly in the automation business." },
    { keywords: ["tech", "technology", "technologies", "digital", "software", "labs"], mod: 1.12, note: "A tech company means AI adoption is fast-tracked. Engineering and digital roles here are on the automation frontline." },
    { keywords: ["data", "analytics", "insight"], mod: 1.14, note: "Data-driven companies are prime AI adopters. If your work involves data, AI already does it better." },
    { keywords: ["automation", "automate", "robotic", "bot"], mod: 1.24, note: "This company literally has 'automation' in its DNA." },
    { keywords: ["cloud", "saas", "platform"], mod: 1.10, note: "Cloud and SaaS companies are at the forefront of AI integration." },
    { keywords: ["fintech", "payments", "finance tech"], mod: 1.12, note: "Fintech companies are among the most aggressive AI adopters." },
    { keywords: ["consulting", "advisory", "solutions"], mod: 1.06, note: "Consulting firms are using AI to do what junior consultants used to do." },
    { keywords: ["startup"], mod: 1.08, note: "Startups move fast and adopt AI faster." },
    { keywords: ["bank", "banking", "financial"], mod: 1.06, note: "Banking is being transformed by AI." },
    { keywords: ["hospital", "health", "medical", "pharma", "clinic"], mod: 0.88, note: "Healthcare organizations are cautious AI adopters due to regulations." },
    { keywords: ["school", "university", "college", "education", "academy"], mod: 0.85, note: "Educational institutions are slow to adopt AI for replacement." },
    { keywords: ["government", "govt", "municipal", "ministry", "department"], mod: 0.78, note: "Government bodies are the slowest to adopt AI. Bureaucracy is your best job security." },
    { keywords: ["factory", "manufacturing", "industrial"], mod: 0.95, note: "Manufacturing is seeing AI in quality control and planning." },
];

// ---- Task keyword modifiers ----
export const TASK_KEYWORDS_UP = [
    { keywords: ["data entry", "typing", "copy paste", "copy-paste", "filing", "scanning"], weight: 10 },
    { keywords: ["scheduling", "calendar", "booking", "appointments"], weight: 8 },
    { keywords: ["email", "correspondence", "replying", "inbox"], weight: 5 },
    { keywords: ["report", "reporting", "documentation", "documenting"], weight: 7 },
    { keywords: ["spreadsheet", "excel", "tally", "erp", "sap"], weight: 7 },
    { keywords: ["writing", "content writing", "blog", "articles", "captions"], weight: 6 },
    { keywords: ["testing", "manual testing", "test cases"], weight: 7 },
    { keywords: ["sorting", "organizing", "categorizing", "tagging"], weight: 8 },
    { keywords: ["translation", "transcription", "subtitles"], weight: 9 },
    { keywords: ["answering calls", "phone calls", "tickets", "support tickets"], weight: 7 },
    { keywords: ["social media", "posting", "reels", "tweets"], weight: 6 },
    { keywords: ["proofreading", "editing text", "grammar"], weight: 7 },
    { keywords: ["invoicing", "billing", "payroll processing"], weight: 8 },
    { keywords: ["wireframe", "wireframing", "mockup", "ui design", "figma", "sketch"], weight: 6 },
    { keywords: ["presentations", "slides", "ppt", "powerpoint"], weight: 5 },
    { keywords: ["basic coding", "html", "css", "simple scripts"], weight: 4 },
];

export const TASK_KEYWORDS_DOWN = [
    { keywords: ["leadership", "leading", "mentoring", "coaching"], weight: -8 },
    { keywords: ["strategy", "strategic", "vision", "roadmap"], weight: -7 },
    { keywords: ["negotiation", "negotiating", "closing deals", "persuading"], weight: -6 },
    { keywords: ["client relations", "stakeholder management", "relationship building"], weight: -5 },
    { keywords: ["creative direction", "brainstorming", "ideation", "innovation"], weight: -5 },
    { keywords: ["managing teams", "people management", "team building", "hiring"], weight: -7 },
    { keywords: ["architecture", "system design", "designing systems"], weight: -6 },
    { keywords: ["crisis management", "incident response"], weight: -4 },
    { keywords: ["public speaking", "pitching", "keynote"], weight: -5 },
    { keywords: ["physical", "hands-on", "manual labor", "fieldwork"], weight: -8 },
    { keywords: ["empathy", "counseling", "therapy", "patient care"], weight: -9 },
    { keywords: ["deep research", "original research", "r&d"], weight: -5 },
];

// ---- Loading messages ----
export const LOADING_MESSAGES = [
    { text: "Scanning your career DNA...", sub: "This might sting a little." },
    { text: "Consulting the AI overlords...", sub: "They're already laughing." },
    { text: "Digging your career's grave...", sub: "6 feet should be enough, right?" },
    { text: "Measuring your replaceability...", sub: "Spoiler: it's not looking great." },
    { text: "Researching your organisation...", sub: "Their AI budget is... concerning." },
    { text: "Cross-referencing AI capabilities...", sub: "AI capabilities: ∞. Yours: finite." },
    { text: "Analyzing your daily tasks...", sub: "AI is taking detailed notes. Literally." },
    { text: "Calculating your termination date...", sub: "Hope you like surprises." },
    { text: "Generating career autopsy report...", sub: "Cause of death: automation." },
    { text: "Preparing your doom card...", sub: "It'll look great on LinkedIn. As a memorial." },
];
